language: cpp

sudo: required
dist: focal

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt-5.14.2-bionic
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qt515base qt515tools libgl-dev; source /opt/qt515/bin/qt515-env.sh
- sudo apt-get install -qq liblscp-dev libgig-dev

before_script:
- git fetch --unshallow --tags -q
- ./autogen.sh

script:
- ./configure
- make
- sudo make install
